Implement generic operators
Bitspark/slang pull request #55
Opened 2018-01-08 00:35 UTC by jm9e

This PR does *not* implement type inference. Rather, it adds the possibility to specify a placeholder type (called `generic`) in the ports definitions. When instancing such an operator, you have to specify the type in the `generics` field of an instance. This introduces generic operators.

It also makes run the old tests and is fully compatible with the builtin operators.

Tests run successfully of course (including the complex suits test).

What still needs to be done:
- [x] Write tests
- [x] Add explanatory  comments
- [x] Review *thoroughly*
  
Closes #38 #49

2018-01-09 23:05 UTC, jm9e commented on builtin/eval.go
> +			Type:    "generic",
I chose to call our new generic type `generic` instead of `any`. I think this is more intuitive.

2018-01-09 23:06 UTC, jm9e commented on builtin/eval_test.go
> +		},
Every operator instance of a generic operator (i.e. an operator which contains generic types) must have a generic map attached to it. This map is used to replace the generic types with the actual types which are known at the time of instancing.

2018-01-09 23:07 UTC, jm9e commented on builtin/eval_test.go
> +	fo.In().Push(map[string]interface{}{"a": true, "b": 8.0, "c": 8.0})
I noticed that I used `number` for `b` and `c` so I adapted the values accordingly. It would have worked with the old values too of course.

2018-01-09 23:10 UTC, jm9e commented on builtin/manager.go
> +	out := cfg.oDef.Out.Copy()
`in` and `out` have to be copied safely. This has to be done because `SpecifyGenericPorts` (see below) actually changes the port definition. However we **must not** change the static port definitions of our builtin operators. That's why we copy them before modifying them to leave `cfg.oDef` untouched.

2018-01-09 23:11 UTC, jm9e commented on builtin/manager.go
> +	}
We want to ensure that the builtin operator is now free of any generics. This is very important because many builtin operators rely on pulling the correct datastructure. `Pull` however can only pull the correct datastructure if the type is correct. But `generic` is not a type we can pull from, so we don't allow it!

2018-01-09 23:14 UTC, jm9e commented on builtin/manager.go
> +	}
`SpecifyGenericPorts` makes sure that pointer definitions are copied and not changed. This is very important as can be read above. See also implementation of `SpecifyGenericPorts`.

2018-01-09 23:17 UTC, jm9e commented on core/def.go
> +	Out         PortDef             `json:"out"`
We use no pointers for safety reasons. Changing the port definition could affect other operator definitions otherwise.

2018-01-09 23:18 UTC, jm9e commented on core/def.go
> +// INSTANCE DEFINITION
I chose to restructure the file a bit. This is because different definition structs have very different methods now, so grouping by methods would not make much sense anymore.

2018-01-10 17:03 UTC, td5r requested changes
What I have understand is:
- When defining a builtin.Operator, one can specify In and Out as generic.
- When using that builtin.Operator, you have to specify in InstanceDef the field "generics"

My Question:
Does that mean, one can only specify 1 Generic in InstanceDef for all generics of OperatorDef?

I would recommended, we should revise this whole topic on friday. This is a very fundamental change for this project. Asap you have answered my questions, I will approve and merge this PR.

2018-01-10 17:03 UTC, td5r commented on core/def.go
> +	operatorDefSet bool
`operatorDefSet` indicates whether `operatorDef` is nil or not nil. What is the purpose of `operatorDef` within `instanceDef`?
Why do we need an additional flag for indicating `operatorDef!=nil`

2018-01-10 17:03 UTC, td5r commented on core/def.go
> +	return d.operatorDefSet
why not `return d.operatorDef!=nil`

2018-01-10 17:03 UTC, td5r commented on core/def.go
> +// SpecifyGenericPorts specifies generic types in the operator definition. It does not touch referenced values
The first sentence is not very helpful. Its just the same as the function name but with extra words.

Here you have to explain what specifying a generic port really means.

2018-01-10 17:03 UTC, td5r commented on core/def.go
> +func (d OperatorDef) FreeOfGenerics() error {
Suggestion: Rename `FreeOfGenerics` into `IsSpecified`

2018-01-10 17:03 UTC, td5r commented on core/def.go
>  	Operator   string                 `json:"operator"`
We must add all possible *identifier* as commends to ...Defs.
e.g.
```
type PortDef struct {
    // "map", "stream" ... 
   Type ...
}
```

2018-01-10 17:03 UTC, td5r commented on core/def.go
> +			for k, e := range d.Map {
Shouldn't we copy d.Map, too?

2018-01-10 17:03 UTC, td5r commented on core/port.go
> +		name = "generic"
why not all uppercase?

2018-01-10 17:03 UTC, td5r commented on slang.go
> +// generics map given. The generics map must not contain any further generic types.
👍

2018-01-10 18:46 UTC, jm9e commented on core/port.go
> +		name = "generic"
Will change.

2018-01-10 19:30 UTC, jm9e commented on core/def.go
> +			for k, e := range d.Map {
We may change values of `d` (including `d.map`). What we must not do is assign references as this would create dependencies and would be a potential source of errors.

2018-01-10 19:33 UTC, jm9e commented on core/def.go
> +func (d OperatorDef) FreeOfGenerics() error {
Don't you think `FreeOfGenerics` is clearer than `IsSpecified`? You wouldn't immediately know what is specified whereas `FreeOfGenerics` is quite clear in that regard. What do you think of `GenericsSpecified`?

2018-01-10 19:35 UTC, jm9e commented on core/def.go
> +	operatorDefSet bool
Because `operatorDef` is not a pointer and cannot be nil. But you are right, this seems akward. See below.

2018-01-10 19:35 UTC, jm9e commented on core/def.go
> +	return d.operatorDefSet
I simply took `Valid()` now and removed the method entirely. This should serve the same purpose as empty `OperatorDef`s have an invalid in and out port.

2018-01-10 19:43 UTC, jm9e commented on core/def.go
> +// SpecifyGenericPorts specifies generic types in the operator definition. It does not touch referenced values
Point taken.

2018-01-10 19:45 UTC, jm9e commented
@tidify Not sure if I got you right, but I will try to explain it:
* An operator can have generic types in its in port and out port
* The whole in and out port can be generic or parts of it (in a map for example)
* Each generic type has an identifier
* This identifier is not unique however; they identify a group of ports which all share the same generic type
* In an instance definition you can replace these groups of generic ports with actual types

2018-01-10 19:46 UTC, jm9e commented on core/def.go
>  	Operator   string                 `json:"operator"`
Done.

2018-01-10 21:52 UTC, td5r commented on core/def.go
>  func (d *OperatorDef) SpecifyGenericPorts(generics map[string]*PortDef) error {
this is what I call a neat docstring ;-)

2018-01-10 21:58 UTC, td5r commented on core/def.go
> +	return d.operatorDefSet
👍

2018-01-10 21:58 UTC, td5r approved these changes

2018-01-10 21:59 UTC, merged