Implement builtin.Take
Bitspark/slang pull request #78
Opened 2018-02-10 19:25 UTC by jm9e

- Implement operator
- Add tests

2018-02-11 20:31 UTC, td5r requested changes

2018-02-11 20:31 UTC, td5r commented on builtin/take_test.go
> +func TestOperator_Take__Simple1(t *testing.T) {
this test function looks way to complex. 
Can you split this into different smaller tests?

2018-02-11 20:31 UTC, td5r commented on core/def.go
> +			// Replace with copy!
I guess this comment is obsolete, isn't it?

2018-02-11 20:31 UTC, td5r commented on core/def.go
>  				// Replace with copy!
may this, too?

2018-02-11 20:31 UTC, td5r commented on slang.go
> +	relFilePath := insDef.Operator
1) what is happening here?
2) why not a separate function
3) I know todos in code are written quickly, but if they are relevant, then they must become a issue. 

... We should modularize more often our code, especially while implementing builtin.Operators.
In Slang function got way to bloated.

is it ok, to have operators access like `.........op`? <--- this is insecure!
should we allow accessing parent dirs?

2018-02-11 20:31 UTC, td5r commented on builtin/take_test.go
> +	to.Out().Map("compare").Stream().Map("true").Bufferize()
`to.Out().Bufferize()` should also work

2018-02-11 20:31 UTC, td5r commented on builtin/take.go
> +							goto end
Using goto often means bad coding style... maybe revising your implementation could help getting rid of goto?

2018-02-11 20:31 UTC, td5r commented on tests/test_data/sort/merge_sort.yaml
> +  .(:
happy code :)

2018-02-11 23:01 UTC, jm9e commented on core/def.go
>  				// Replace with copy!
Well, these comments are not really necessary. I just wanted to stress how important it is to replace all pointers with pointers to fresh instances.

2018-02-11 23:03 UTC, jm9e commented on builtin/take.go
> +							goto end
Often but not always. All of us were taught to avoid gotos (including me), but there is a reason why they are included in Golang. Here is a well perceived answer mentioning two possible use cases for goto: https://stackoverflow.com/questions/24451/is-it-ever-advantageous-to-use-goto-in-a-language-that-supports-loops-and-func/24476#24476 Here, case 2 applies.

Notice that Java (which does not have gotos) has other language constructs instead (loop labels). Since golang doesn't have it, goto is OK here in my opinion.

2018-02-11 23:04 UTC, jm9e commented on builtin/take_test.go
> +	to.Out().Map("compare").Stream().Map("true").Bufferize()
Will replace it. Was not available yet when I was developing this.

2018-02-11 23:09 UTC, jm9e commented on slang.go
> +	relFilePath := insDef.Operator
Point accepted. Will remove accessing parent dirs. I was aware of the fact it could be unsecure. But it probably is never a good idea to access the parent directory and a sign of bad design.

2018-02-11 23:16 UTC, jm9e commented on builtin/take_test.go
> +func TestOperator_Take__Simple1(t *testing.T) {
I agree it is hard to read and seems too big. The problem here is that `reduce` has a very complicated behavior requiring data for `items` before it even considers items in `pool`. It also needs to be feeded correct `BOS` and `EOS` markers. So to test correct behavior for the last `EOS` it needs a long series of other input, which is done in this test.

2018-02-15 21:13 UTC, td5r approved these changes

2018-02-15 21:13 UTC, merged